name: Example workflow using Snyk
on: push
jobs:
  security:
    runs-on: self-hosted
    steps:
    - name: pull source
      working-directory: /opt/snyk/PQShopWithNodeJs
      run: |
        git fetch --all
        git clean -fd
        git clean -f -X
        git checkout main
        git reset --hard origin/main
        git pull --rebase=false origin --prune --verbose
        git status
        snyk test
